### ISSUE TITLE
Improve documentation for uploading data

### ISSUE THREAD

**Issue by gschivley** [NREL/GridSight#9]
Documentation on the project is pretty thin right now. I've created some sample data sets and was able to get docker up and running. At that point I can see a nice map of the US and interact with the sidebar, etc. But I haven't figured out how to post the data. `localhost` ports 5001 and 3000 don't work. Any suggestions?

**Comment by micahpw** [comment]
Hi @gschivley, I've updated the documentation and included a client module, demo data, and an upload script in the repository now. You should be using port 3000 to upload data. The backend API will be rewritten in FastAPI fairly soon to enable some of the items on the roadmap. I will also update the client api to make it easier to upload data going forward.

Let me know if you still run into trouble or if you have any more questions.
-Micah
